# Site settings
title: Christian Duque-Arribas
description: C. Duque-Arribas personal webpage
baseurl: https://chrduque.astro
url: https://chrduque.astro

# User settings
username: Christian Duque-Arribas
user_description: I'm an astrophysics PhD student studying the metallicity and chemical abundances in M-type dwarf stars at Universidad Complutense de Madrid (Spain), <a href="https://www.ucm.es/iparcos/" target="_blank">IPARCOS-UCM</a> & <a href="https://carmenes.caha.es" target="_blank">CARMENES</a>
user_title: Astrophysicist | PhD student
email: chrduque@ucm.es
twitter_username: chrduque
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: chrduque
github_username:  chrduque
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
