# Site settings
title: Christian Duque-Arribas
description: C. Duque-Arribas personal webpage
baseurl: https://chrduque.github.io
url: https://chrduque.github.io

# User settings
username: Christian Duque-Arribas
user_description: I'm an astrophysics PhD student studying the metallicity and chemical abundances in M-type dwarf stars at Universidad Complutense de Madrid (Spain). <br> IPARCOS-UCM & CARMENES
user_title: Astrophysicist | PhD student
email: chrduque@ucm.es
twitter_username: chrduque
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: chrduque
github_username:  chrduque
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
